# Generated by Django 3.1.6 on 2021-03-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankDetails',
            fields=[
                ('bloodbank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('pincode', models.CharField(default='', max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('iso_certified', models.CharField(max_length=5)),
            ],
            options={
                'db_table': ('BloodBankDetails',),
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=4)),
                ('dob', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=15)),
                ('availability', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=4)),
                ('age', models.CharField(max_length=3)),
                ('required_date', models.DateField()),
                ('blood_unit', models.CharField(max_length=4)),
                ('mobile_no', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('patient_address', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=150)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.userdetails')),
            ],
            options={
                'db_table': ('RequestDetails',),
            },
        ),
        migrations.CreateModel(
            name='AvailableBloodGroup',
            fields=[
                ('blood_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=4)),
                ('available_units', models.CharField(max_length=50)),
                ('bloodbank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.bloodbankdetails')),
            ],
            options={
                'db_table': 'AvailableBloodGroup',
            },
        ),
    ]
